# Documentation: https://roots.io/trellis/docs/mail/
mail_smtp_server: smtp.greatsouthwest.co:587
mail_admin: admin@greatsouthwest.co
mail_hostname: greatsouthwest.co
mail_user: smtp_user
mail_password: "{{ vault_mail_password }}" # Define this variable in group_vars/all/vault.yml
